name: VPS cloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup XFCE + VNC + noVNC + ngrok
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies xfce4-terminal tightvncserver novnc websockify curl

          # Configurar VNC sem senha
          mkdir -p ~/.vnc
          echo "123456" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          # Inicia o VNC no display :1
          vncserver :1 -geometry 1280x720 -depth 24 -xstartup /usr/bin/startxfce4

          # Instala ngrok
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com bookworm main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install -y ngrok

          # Configura o token do ngrok
          ngrok config add-authtoken 31LIbARpjT7EzZwTkP9HYpnrsNW_3j14ancc7YwieRbDq5Lwe

          # Inicia noVNC via websockify
          websockify --web /usr/share/novnc/ 5901 localhost:5901 &

          # Cria túnel ngrok para noVNC
          ngrok http 5901 --log=stdout &
